spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.data-source-properties.ApplicationName=quizards-local
spring.datasource.hikari.data-source-properties.prepareThreshold=0
